# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/borisshapa/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.7141.37/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/borisshapa/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.7141.37/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/borisshapa/cpp-course/huffman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/borisshapa/cpp-course/huffman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/borisshapa/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.7141.37/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/borisshapa/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.7141.37/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/borisshapa/cpp-course/huffman/CMakeFiles /home/borisshapa/cpp-course/huffman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/borisshapa/cpp-course/huffman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HuffmanCompresser

# Build rule for target.
HuffmanCompresser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HuffmanCompresser
.PHONY : HuffmanCompresser

# fast build rule for target.
HuffmanCompresser/fast:
	$(MAKE) -f CMakeFiles/HuffmanCompresser.dir/build.make CMakeFiles/HuffmanCompresser.dir/build
.PHONY : HuffmanCompresser/fast

#=============================================================================
# Target rules for targets named Testing

# Build rule for target.
Testing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Testing
.PHONY : Testing

# fast build rule for target.
Testing/fast:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/build
.PHONY : Testing/fast

lib/decoder.o: lib/decoder.cpp.o

.PHONY : lib/decoder.o

# target to build an object file
lib/decoder.cpp.o:
	$(MAKE) -f CMakeFiles/HuffmanCompresser.dir/build.make CMakeFiles/HuffmanCompresser.dir/lib/decoder.cpp.o
.PHONY : lib/decoder.cpp.o

lib/decoder.i: lib/decoder.cpp.i

.PHONY : lib/decoder.i

# target to preprocess a source file
lib/decoder.cpp.i:
	$(MAKE) -f CMakeFiles/HuffmanCompresser.dir/build.make CMakeFiles/HuffmanCompresser.dir/lib/decoder.cpp.i
.PHONY : lib/decoder.cpp.i

lib/decoder.s: lib/decoder.cpp.s

.PHONY : lib/decoder.s

# target to generate assembly for a file
lib/decoder.cpp.s:
	$(MAKE) -f CMakeFiles/HuffmanCompresser.dir/build.make CMakeFiles/HuffmanCompresser.dir/lib/decoder.cpp.s
.PHONY : lib/decoder.cpp.s

lib/encoder.o: lib/encoder.cpp.o

.PHONY : lib/encoder.o

# target to build an object file
lib/encoder.cpp.o:
	$(MAKE) -f CMakeFiles/HuffmanCompresser.dir/build.make CMakeFiles/HuffmanCompresser.dir/lib/encoder.cpp.o
.PHONY : lib/encoder.cpp.o

lib/encoder.i: lib/encoder.cpp.i

.PHONY : lib/encoder.i

# target to preprocess a source file
lib/encoder.cpp.i:
	$(MAKE) -f CMakeFiles/HuffmanCompresser.dir/build.make CMakeFiles/HuffmanCompresser.dir/lib/encoder.cpp.i
.PHONY : lib/encoder.cpp.i

lib/encoder.s: lib/encoder.cpp.s

.PHONY : lib/encoder.s

# target to generate assembly for a file
lib/encoder.cpp.s:
	$(MAKE) -f CMakeFiles/HuffmanCompresser.dir/build.make CMakeFiles/HuffmanCompresser.dir/lib/encoder.cpp.s
.PHONY : lib/encoder.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

utility/console.o: utility/console.cpp.o

.PHONY : utility/console.o

# target to build an object file
utility/console.cpp.o:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/utility/console.cpp.o
.PHONY : utility/console.cpp.o

utility/console.i: utility/console.cpp.i

.PHONY : utility/console.i

# target to preprocess a source file
utility/console.cpp.i:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/utility/console.cpp.i
.PHONY : utility/console.cpp.i

utility/console.s: utility/console.cpp.s

.PHONY : utility/console.s

# target to generate assembly for a file
utility/console.cpp.s:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/utility/console.cpp.s
.PHONY : utility/console.cpp.s

utility/util.o: utility/util.cpp.o

.PHONY : utility/util.o

# target to build an object file
utility/util.cpp.o:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/utility/util.cpp.o
.PHONY : utility/util.cpp.o

utility/util.i: utility/util.cpp.i

.PHONY : utility/util.i

# target to preprocess a source file
utility/util.cpp.i:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/utility/util.cpp.i
.PHONY : utility/util.cpp.i

utility/util.s: utility/util.cpp.s

.PHONY : utility/util.s

# target to generate assembly for a file
utility/util.cpp.s:
	$(MAKE) -f CMakeFiles/Testing.dir/build.make CMakeFiles/Testing.dir/utility/util.cpp.s
.PHONY : utility/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... HuffmanCompresser"
	@echo "... Testing"
	@echo "... lib/decoder.o"
	@echo "... lib/decoder.i"
	@echo "... lib/decoder.s"
	@echo "... lib/encoder.o"
	@echo "... lib/encoder.i"
	@echo "... lib/encoder.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
	@echo "... utility/console.o"
	@echo "... utility/console.i"
	@echo "... utility/console.s"
	@echo "... utility/util.o"
	@echo "... utility/util.i"
	@echo "... utility/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

